<?php 

/*
 * @file 
 * 
 * openscholar statistics block module
 */

/*
 * Implementation of hook_block
 */
 function os_stats_block($op = 'list', $delta = 0, $edit = array()) {
 	switch($op) {
 		case 'list':
 			$blocks[0]['info'] = t('OpenScholar Statistics');
 			$blocks[0]['cache'] = BLOCK_CACHE_GLOBAL;
 			return $blocks;
 			break;
 		case 'view':
 			$block['subject'] = "OpenScholar Statistics";
 			$block['content'] = _os_stats_content();
 			return $block;
 			break;
 			
 	}
 
 }
 
function _os_stats_content() {
	$out = "";
	
	//check cache
	if ($cache = cache_get('os_stats_data')) {
		$out .= "cached:<br />";
		$out .= unserialize($cache->data);
	} else {
		//build and store data
		//publications
		$query = "SELECT COUNT(nid) FROM {node} WHERE type='biblio'";
		$result = db_result(db_query($query));
		$out .= "Publications: $result<br />";

		$query = "SELECT COUNT(nid) FROM {og}";
		$result = db_result(db_query($query));
		$out .= "Vsites: $result<br />";
		
		
		cache_set('os_stats_data', serialize($out), 'cache', time() + 60);
		
		$out = "uncached...rebuilding<Br />" . $out;
	}
	
	return $out;
}